ALTER TABLE outfit_items
    ADD COLUMN position_x REAL NOT NULL DEFAULT 0,
    ADD COLUMN position_y REAL NOT NULL DEFAULT 0,
    ADD COLUMN scale REAL NOT NULL DEFAULT 1.0,
    ADD COLUMN z_index INT NOT NULL DEFAULT 0;
